apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jobblo
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: jobblo.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: jobblo
                port:
                  number: 80


#Husk Ã¥ justere host: jobblo.local til et faktisk domene eller lokal DNS-oppse
