name: pre-commit

on:
  pull_request:

jobs:
  pre-commit:
    name: "ğŸ” Pre-commit"
    runs-on: ubuntu-latest
    steps:
      - name: "ğŸ›ï¸ Checkout code"
        uses: actions/checkout@v4

      - name: "ğŸ Setup Python"
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'  # Eller versjonen du bruker

      - name: "ğŸ“¦ Install dependencies (optional)"
        run: |
          python -m pip install --upgrade pip
          pip install pre-commit

      - name: "ğŸ” Run pre-commit checks"
        uses: pre-commit/action@v3.0.1
