name: build_and_push_container
# testrun2
on:
  workflow_call:

permissions:
  id-token: write
  contents: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0
        with:
          versionSpec: '5.x'

      - name: Determine Version
        id: gitversion
        uses: gittools/actions/gitversion/execute@v0
        with:
          useConfigFile: true

      - name: Tag commit
        run: |
          git tag ${{ steps.gitversion.outputs.fullSemVer }}
          git push origin ${{ steps.gitversion.outputs.fullSemVer }}
          git fetch

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Log in to Azure Container Registry (admin user)
        uses: azure/docker-login@v2
        with:
          login-server: ${{ secrets.ACR_LOGIN_SERVER }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Set image variables
        id: vars
        run: |
          echo "IMAGE_TAG=${{ steps.gitversion.outputs.fullSemVer }}" >> $GITHUB_ENV
          echo "IMAGE_NAME=${{ secrets.ACR_LOGIN_SERVER }}/jobblo/backend" >> $GITHUB_ENV
        env:
          ACR_LOGIN_SERVER: ${{ secrets.ACR_LOGIN_SERVER }}

      - name: Build Docker image
        run: |
          echo "Building Docker image: $IMAGE_NAME:$IMAGE_TAG"
          docker buildx build -f backend/Dockerfile -t $IMAGE_NAME:$IMAGE_TAG "."

      - name: Push Docker image
        run: |
          echo "Pushing Docker image: $IMAGE_NAME:$IMAGE_TAG"
          docker push $IMAGE_NAME:$IMAGE_TAG

      - name: Update Azure Container App
        run: |
          echo "Updating Azure Container App with image: $IMAGE_NAME:$IMAGE_TAG"
          az containerapp update \
            --name jobblo-container-app \
            --resource-group jobblo-rg \
            --image $IMAGE_NAME:$IMAGE_TAG
